Outputs:
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt 'myinstance1.PublicIp'
Parameters:
  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  myinstance1:
    Properties:
      ImageId: ami-0eaec5838478eb0ba
      InstanceType: t2.micro
      KeyName: !Ref 'SshKeyName'
      Tags:
        - Key: name
          Value: my_instance1
    Type: AWS::EC2::Instance

